// Code generated by angular2-stress-test

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
    buildType :string;
    ngOnInit(){
      this.buildType = process.env.TYPE
    }
}
